# --- !Ups


create table "BOOK" (
  "ID" VARCHAR NOT NULL PRIMARY KEY,
  "TITLE" VARCHAR NOT NULL,
  "SUMMARY" VARCHAR,
  "ISBN" VARCHAR,
  "GENRE" VARCHAR REFERENCES GENRE("NAME")
);

create table "BOOK_AUTHOR" (
  "BOOK_ID" VARCHAR NOT NULL REFERENCES BOOK("ID"),
  "AUTHOR_ID" VARCHAR NOT NULL REFERENCES AUTHOR("ID"),
  PRIMARY KEY ("BOOK_ID", "AUTHOR_ID")
);

# --- !Downs

drop table "BOOK_AUTHOR";
drop table "BOOK";
